// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​P​o​s​t​A​p​p
	 */
	WELCOME: string
	/**
	 * H​o​m​e
	 */
	HOME: string
	/**
	 * L​o​g​i​n
	 */
	LOGIN: string
	/**
	 * R​e​g​i​s​t​e​r
	 */
	REGISTER: string
	/**
	 * C​r​e​a​t​e​ ​P​o​s​t
	 */
	CREATE_POST: string
	/**
	 * L​o​g​o​u​t
	 */
	LOGOUT: string
	/**
	 * P​u​b​l​i​s​h​ ​P​o​s​t
	 */
	PUBLISH: string
	/**
	 * C​o​n​t​e​n​t
	 */
	CONTENT: string
	/**
	 * T​i​t​l​e
	 */
	TITLE: string
	/**
	 * L​o​a​d​ ​m​o​r​e​ ​p​o​s​t​s
	 */
	LOAD_MORE: string
	/**
	 * N​o​ ​p​o​s​t​s​ ​y​e​t​.​ ​B​e​ ​t​h​e​ ​f​i​r​s​t​!
	 */
	NO_POSTS: string
	/**
	 * W​e​l​c​o​m​e​ ​B​a​c​k
	 */
	LOGIN_WELCOME: string
	/**
	 * J​o​i​n​ ​U​s
	 */
	JOIN_US: string
	/**
	 * N​e​w​ ​P​o​s​t
	 */
	NEW_POST: string
	/**
	 * E​n​t​e​r​ ​a​ ​c​a​t​c​h​y​ ​t​i​t​l​e​.​.​.
	 */
	ENTER_TITLE: string
	/**
	 * S​h​a​r​e​ ​y​o​u​r​ ​s​t​o​r​y​.​.​.
	 */
	STORY_PLACEHOLDER: string
	/**
	 * P​u​b​l​i​s​h​e​d​ ​o​n​ ​{​d​a​t​e​}
	 * @param {unknown} date
	 */
	PUBLISHED_ON: RequiredParams<'date'>
	/**
	 * N​e​e​d​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​S​i​g​n​ ​u​p
	 */
	NEED_ACCOUNT: string
	/**
	 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​L​o​g​i​n
	 */
	ALREADY_HAVE_ACCOUNT: string
	/**
	 * T​i​t​l​e​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	VALIDATION_TITLE_REQUIRED: string
	/**
	 * T​i​t​l​e​ ​t​o​o​ ​l​o​n​g​ ​(​m​a​x​ ​1​0​0​ ​c​h​a​r​a​c​t​e​r​s​)
	 */
	VALIDATION_TITLE_TOO_LONG: string
	/**
	 * C​o​n​t​e​n​t​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	VALIDATION_CONTENT_REQUIRED: string
	/**
	 * P​o​s​t​ ​n​o​t​ ​f​o​u​n​d
	 */
	ERROR_POST_NOT_FOUND: string
	/**
	 * U​n​a​u​t​h​o​r​i​z​e​d
	 */
	ERROR_UNAUTHORIZED: string
}

export type TranslationFunctions = {
	/**
	 * Welcome to PostApp
	 */
	WELCOME: () => LocalizedString
	/**
	 * Home
	 */
	HOME: () => LocalizedString
	/**
	 * Login
	 */
	LOGIN: () => LocalizedString
	/**
	 * Register
	 */
	REGISTER: () => LocalizedString
	/**
	 * Create Post
	 */
	CREATE_POST: () => LocalizedString
	/**
	 * Logout
	 */
	LOGOUT: () => LocalizedString
	/**
	 * Publish Post
	 */
	PUBLISH: () => LocalizedString
	/**
	 * Content
	 */
	CONTENT: () => LocalizedString
	/**
	 * Title
	 */
	TITLE: () => LocalizedString
	/**
	 * Load more posts
	 */
	LOAD_MORE: () => LocalizedString
	/**
	 * No posts yet. Be the first!
	 */
	NO_POSTS: () => LocalizedString
	/**
	 * Welcome Back
	 */
	LOGIN_WELCOME: () => LocalizedString
	/**
	 * Join Us
	 */
	JOIN_US: () => LocalizedString
	/**
	 * New Post
	 */
	NEW_POST: () => LocalizedString
	/**
	 * Enter a catchy title...
	 */
	ENTER_TITLE: () => LocalizedString
	/**
	 * Share your story...
	 */
	STORY_PLACEHOLDER: () => LocalizedString
	/**
	 * Published on {date}
	 */
	PUBLISHED_ON: (arg: { date: unknown }) => LocalizedString
	/**
	 * Need an account? Sign up
	 */
	NEED_ACCOUNT: () => LocalizedString
	/**
	 * Already have an account? Login
	 */
	ALREADY_HAVE_ACCOUNT: () => LocalizedString
	/**
	 * Title is required
	 */
	VALIDATION_TITLE_REQUIRED: () => LocalizedString
	/**
	 * Title too long (max 100 characters)
	 */
	VALIDATION_TITLE_TOO_LONG: () => LocalizedString
	/**
	 * Content is required
	 */
	VALIDATION_CONTENT_REQUIRED: () => LocalizedString
	/**
	 * Post not found
	 */
	ERROR_POST_NOT_FOUND: () => LocalizedString
	/**
	 * Unauthorized
	 */
	ERROR_UNAUTHORIZED: () => LocalizedString
}

export type Formatters = {}
